//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2001200647_QLNUOCGIAIKHAT.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart1
    {
        internal int iSoLuong;
        internal int iThanhTien;
        internal int iCategoryID;

        public Cart1(int ms)
        {
            Ms = ms;
        }

        public int CategoryID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Price { get; set; }
        public string FullDescription { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public string Image { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public int Ms { get; }
    }
}
